"""Add compliance models and triggers

Revision ID: cae7caeedc2f
Revises: a097254208ad
Create Date: 2026-04-18 09:52:38.782148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cae7caeedc2f'
down_revision: Union[str, Sequence[str], None] = 'a097254208ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop in correct order
    op.execute('DROP TABLE IF EXISTS compliance_rules CASCADE;')
    op.execute('DROP TABLE IF EXISTS zoning_codes CASCADE;')
    op.execute('DROP TABLE IF EXISTS regions CASCADE;')
    op.execute('DROP TABLE IF EXISTS property_compliance CASCADE;')
    op.execute('DROP TABLE IF EXISTS municipal_codes CASCADE;')
    
    op.create_table('municipal_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipality_name', sa.String(length=100), nullable=False),
    sa.Column('ordinance_number', sa.String(length=50), nullable=False),
    sa.Column('str_prohibited', sa.Boolean(), nullable=True),
    sa.Column('max_occupancy_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('length(municipality_name) > 0', name='chk_mun_name_length'),
    sa.CheckConstraint("ordinance_number ~ '^[A-Z0-9-]+$'", name='chk_ordinance_format')
    )
    
    op.create_table('property_compliance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('municipal_code_id', sa.UUID(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('violation_notes', sa.String(length=500), nullable=True),
    sa.Column('valid_period', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['municipal_code_id'], ['municipal_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_property_compliance_valid_period', 'property_compliance', ['property_id', 'valid_period'], unique=False, postgresql_using='gist')

    op.execute('''
    CREATE OR REPLACE FUNCTION enforce_append_only_compliance()
    RETURNS TRIGGER AS $$
    BEGIN
        IF TG_OP = 'UPDATE' THEN
            RAISE EXCEPTION 'Cannot modify historical compliance records. Append-only temporal versioning enforced.';
        END IF;
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'Cannot delete compliance records. Append-only temporal versioning enforced.';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    DROP TRIGGER IF EXISTS trg_close_expired_compliance ON property_compliance;
    CREATE TRIGGER trg_close_expired_compliance
    BEFORE UPDATE OR DELETE ON property_compliance
    FOR EACH ROW EXECUTE FUNCTION enforce_append_only_compliance();
    ''')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_compliance', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'property_compliance', type_='foreignkey')
    op.create_foreign_key(op.f('property_compliance_municipal_code_id_fkey'), 'property_compliance', 'municipal_codes', ['municipal_code_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_property_compliance_valid_period', table_name='property_compliance', postgresql_using='gist')
    op.create_index(op.f('ix_prop_comp_property_valid_period_gist'), 'property_compliance', ['property_id', 'valid_period'], unique=False, postgresql_using='gist')
    op.alter_column('property_compliance', 'municipal_code_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('property_compliance', 'property_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('property_compliance', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('property_compliance', 'created_at')
    op.drop_column('property_compliance', 'violation_notes')
    op.drop_column('property_compliance', 'is_compliant')
    op.add_column('municipal_codes', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('municipal_codes', sa.Column('ordinance_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('municipal_codes', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('municipal_codes', 'updated_at')
    op.drop_column('municipal_codes', 'max_occupancy_limit')
    op.drop_column('municipal_codes', 'str_prohibited')
    op.drop_column('municipal_codes', 'ordinance_number')
    op.drop_column('municipal_codes', 'municipality_name')
    op.create_table('regions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('locality', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('admin_area', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('regions_pkey')),
    sa.UniqueConstraint('locality', 'admin_area', name=op.f('uq_region_locality_admin'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('zoning_codes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('zoning_codes_region_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('zoning_codes_pkey')),
    sa.UniqueConstraint('region_id', 'code_name', name=op.f('uq_zoning_region_code'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zoning_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('eligibility_status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_str_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('requires_permit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('min_stay_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_residence_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('plain_english_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permit_application_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ordinance_reference_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['zoning_id'], ['zoning_codes.id'], name=op.f('compliance_rules_zoning_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('compliance_rules_pkey')),
    sa.UniqueConstraint('zoning_id', name=op.f('uq_compliance_zoning'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
