services:
  - type: web
    name: hosteva-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hosteva-db
          property: connectionString

databases:
  - name: hosteva-db
    plan: free
    postgresMajorVersion: "15"
