"""Add municipal compliance models

Revision ID: c656a39f72cf
Revises: 
Create Date: 2026-04-17 12:14:27.131496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c656a39f72cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipal_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ordinance_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("ordinance_id ~ '^[A-Z0-9\\-]+$'", name='chk_ordinance_id_format'),
    sa.CheckConstraint('length(description) <= 500', name='chk_description_length'),
    sa.CheckConstraint('length(ordinance_id) BETWEEN 3 AND 50', name='chk_ordinance_id_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('admin_area', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locality', 'admin_area', name='uq_region_locality_admin')
    )
    op.create_table('property_compliance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('municipal_code_id', sa.String(), nullable=False),
    sa.Column('valid_period', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['municipal_code_id'], ['municipal_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist;')
    op.create_index('ix_prop_comp_property_valid_period_gist', 'property_compliance', ['property_id', 'valid_period'], unique=False, postgresql_using='gist')
    op.create_table('zoning_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('code_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'code_name', name='uq_zoning_region_code')
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('zoning_id', sa.String(), nullable=False),
    sa.Column('eligibility_status', sa.String(length=10), nullable=False),
    sa.Column('is_str_allowed', sa.Boolean(), nullable=False),
    sa.Column('requires_permit', sa.Boolean(), nullable=True),
    sa.Column('min_stay_days', sa.Integer(), nullable=True),
    sa.Column('primary_residence_required', sa.Boolean(), nullable=True),
    sa.Column('plain_english_conditions', sa.Text(), nullable=True),
    sa.Column('permit_application_url', sa.Text(), nullable=True),
    sa.Column('ordinance_reference_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zoning_id'], ['zoning_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zoning_id', name='uq_compliance_zoning')
    )
    
    op.execute('''
    CREATE OR REPLACE FUNCTION prevent_historical_overwrite()
    RETURNS TRIGGER AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'Historical overwrite prevented: Cannot delete from property_compliance';
        END IF;
        
        IF TG_OP = 'UPDATE' THEN
            -- Only allow updates that close the valid_period and do not change other columns
            IF upper_inf(OLD.valid_period) AND NEW.valid_period = tstzrange(lower(OLD.valid_period), upper(NEW.valid_period), '[)') AND NEW.property_id = OLD.property_id AND NEW.municipal_code_id = OLD.municipal_code_id AND NEW.status = OLD.status THEN
                RETURN NEW;
            ELSE
                RAISE EXCEPTION 'Historical overwrite prevented: Can only close active compliance periods.';
            END IF;
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    ''')

    op.execute('''
    CREATE TRIGGER trg_close_expired_compliance
    BEFORE UPDATE OR DELETE ON property_compliance
    FOR EACH ROW
    EXECUTE FUNCTION prevent_historical_overwrite();
    ''')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute('DROP TRIGGER IF EXISTS trg_close_expired_compliance ON property_compliance;')
    op.execute('DROP FUNCTION IF EXISTS prevent_historical_overwrite();')

    op.drop_table('compliance_rules')
    op.drop_table('zoning_codes')
    op.drop_index('ix_prop_comp_property_valid_period_gist', table_name='property_compliance', postgresql_using='gist')
    op.drop_table('property_compliance')
    op.drop_table('regions')
    op.drop_table('municipal_codes')
    # ### end Alembic commands ###
