"""Update compliance constraints

Revision ID: d278a49c96b8
Revises: c656a39f72cf
Create Date: 2026-04-18 06:21:19.436074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd278a49c96b8'
down_revision: Union[str, Sequence[str], None] = 'c656a39f72cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_tasks_id'), table_name='queue_tasks')
    op.drop_index(op.f('ix_queue_tasks_task_name'), table_name='queue_tasks')
    op.drop_table('queue_tasks')
    op.drop_index(op.f('ix_ordinances_id'), table_name='ordinances')
    op.drop_index(op.f('ix_ordinances_jurisdiction'), table_name='ordinances')
    op.drop_table('ordinances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordinances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jurisdiction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordinance_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ordinances_pkey'))
    )
    op.create_index(op.f('ix_ordinances_jurisdiction'), 'ordinances', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_ordinances_id'), 'ordinances', ['id'], unique=False)
    op.create_table('queue_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('queue_tasks_pkey'))
    )
    op.create_index(op.f('ix_queue_tasks_task_name'), 'queue_tasks', ['task_name'], unique=False)
    op.create_index(op.f('ix_queue_tasks_id'), 'queue_tasks', ['id'], unique=False)
    # ### end Alembic commands ###
