import re

with open('/home/rdogen/OpenClaw_Factory/projects/Hosteva/workflow.py', 'r') as f:
    content = f.read()

# We need to map the old variable names to the new ones generated by the regex
old_to_new = {
    'fury_node': 'nick_fury_node',
    'iron_man_arch_node': 'iron_man_arch_node', # didn't change because it was 'Iron Man Arch'
    'spider_man_plan_node': 'spider_man_plan_node',
    'jarvis_vram_node': 'jarvis_vram_node',
    'cap_node': 'captain_america_node',
    'spider_man_env_node': 'spider_man_env_node',
    'rocket_node': 'rocket_raccoon_node'
}

# But wait, looking at the regex, it converted 'Nick Fury' to 'nick_fury_node'
# 'Iron Man Arch' -> 'iron_man_arch_node'
# 'Spider-Man Plan' -> 'spider_man_plan_node'
# 'Captain America' -> 'captain_america_node'
# 'Agent Coulson' -> 'agent_coulson_node'
# 'Jarvis Diag' -> 'jarvis_diag_node'
# 'Spider-Man Env' -> 'spider_man_env_node'
# 'Rocket Raccoon' -> 'rocket_raccoon_node'

# Let's just read the actual variable names from the file
import ast

with open('/home/rdogen/OpenClaw_Factory/projects/Hosteva/workflow.py', 'r') as f:
    lines = f.readlines()

new_nodes_list = []
for line in lines:
    if '_node = Node.agent(' in line:
        var_name = line.split(' =')[0].strip()
        new_nodes_list.append(var_name)

nodes_str = "nodes = [" + ", ".join(new_nodes_list) + ", hawkeye_route_node, cap_route_node, coulson_route_node, spiderman_route_node, heimdall_route_node]"

for i, line in enumerate(lines):
    if line.startswith('nodes = ['):
        lines[i] = nodes_str + '\n'
    elif line.startswith('         hawkeye_node,'):
        lines[i] = ''
    elif line.startswith('         black_widow_node,'):
        lines[i] = ''
    elif line.startswith('         spider_man_env_node,'):
        lines[i] = ''
    elif line.startswith('         shuri_node,'):
        lines[i] = ''

with open('/home/rdogen/OpenClaw_Factory/projects/Hosteva/workflow.py', 'w') as f:
    f.writelines(lines)
